spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  jwt:
    secret: ${jwt_secret}

decorator:
  datasource:
    p6spy:
      enable-logging: true


