spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true

    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  jwt:
    secret: ${jwt_secret}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
  data:
    redis:
      host: ${redis_host}
      port: ${redis_port}
      password : ${redis_password}
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  level:
    org.hibernate.SQL: error

cloud:
  aws:
    credentials:
      accessKey: ${s3_accesskey}
      secretKey: ${s3_secretkey}
    s3:
      bucketName: ${s3_bucketname}
    region:
      static: ap-northeast-2
    stack:
      auto: false




