name: CI

# main,cicd 브랜치에 push, PR 이벤트 발생시 동작.
on:
  push:
    branches:
      - 'main'
      - 'cicd'
  pull_request:
    branches:
      - 'main'
      - 'cicd'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #자바버전 17 세팅
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      #githubsecrets yml 환경변수 주입.
      - name: Set Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: ${{ secrets.DB_URL }}
          spring.datasource.username: ${{ secrets.DB_USERNAME }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}
          spring.datasource.driver-class-name: ${{ secrets.DB_DRIVER }}
          spring.jwt.secret: ${{ secrets.JWT_SECRET }}
          spring.mail.username: ${{secrets.MAIL_USERNAME}}
          spring.mail.password: ${{secrets.MAIL_PASSWORD}}
          spring.data.redis.host: ${{secrets.REDIS_HOST}}
          spring.data.redis.port: ${{secrets.REDIS_PORT}}

      #gradlew 실행을 위한 권한 추가
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Spring Boot 어플리케이션 Build (1)
      - name: Spring Boot Build
        run: ./gradlew clean build -x test